from fpdf import FPDF
import pandas as pd
from datetime import datetime
import io

class PDFReport(FPDF):
    def header(self):
        # Logo or Title Area
        self.set_font("helvetica", "B", 20)
        self.set_text_color(40, 40, 40)
        self.cell(0, 10, "Executive Revenue Report", border=False, align="L")
        self.ln(15)

    def footer(self):
        # Footer Area
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by RevOps Analytics", align="C")

import tempfile
import os

def generate_pdf_report(
    total_revenue: float,
    active_customers: int,
    arpu: float,
    growth_rate: float,
    time_range_label: str,
    top_customers: list,
    ai_summary: str,
    pie_chart_bytes: bytes = None,
    scatter_chart_bytes: bytes = None,
    filtered_risk_lists: dict = None
) -> bytes:
    """
    Generates an executive summary PDF and returns it as a bytes object.
    """
    pdf = PDFReport()
    pdf.add_page()

    # --- Meta Information ---
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"Date Generated: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
    pdf.cell(0, 5, f"Reporting Period: {time_range_label}", ln=True)
    pdf.ln(10)

    # --- AI Executive Summary ---
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "AI Executive Summary", ln=True)
    
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, ai_summary)
    pdf.ln(10)

    # --- Core KPIs ---
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Key Performance Indicators", ln=True)

    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(80, 80, 80)
    
    # Draw KPI cards as text blocks
    kpi_text = (
        f"Total Revenue: ${total_revenue:,.2f}\n"
        f"Active Customers: {active_customers}\n"
        f"ARPU (Avg Revenue Per User): ${arpu:,.2f}\n"
        f"Period Growth Rate: {growth_rate:.2f}%\n"
    )
    pdf.set_font("helvetica", "", 12)
    pdf.multi_cell(0, 8, kpi_text)
    pdf.ln(10)

    # --- Charts ---
    if pie_chart_bytes or scatter_chart_bytes:
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "Visual Analytics", ln=True)
        pdf.ln(5)
        
        y_before = pdf.get_y()
        max_height = 60
        
        if pie_chart_bytes:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_pie:
                tmp_pie.write(pie_chart_bytes)
                tmp_pie_name = tmp_pie.name
            
            # (image name, x, y, width)
            pdf.image(tmp_pie_name, x=10, y=y_before, w=90)
            os.remove(tmp_pie_name)
            
        if scatter_chart_bytes:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_scat:
                tmp_scat.write(scatter_chart_bytes)
                tmp_scat_name = tmp_scat.name
                
            pdf.image(tmp_scat_name, x=105, y=y_before, w=95)
            os.remove(tmp_scat_name)
            
        pdf.set_y(y_before + max_height + 5)
        
    # --- Top Customers Table ---
    if top_customers:
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "Top Performing Customers", ln=True)
        pdf.ln(5)

        # Table Header
        pdf.set_font("helvetica", "B", 11)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(90, 10, "Customer Name", border=1, fill=True)
        pdf.cell(90, 10, "Revenue Contribution", border=1, fill=True, ln=True, align="R")

        # Table Rows
        pdf.set_font("helvetica", "", 11)
        for c in top_customers:
            pdf.cell(90, 10, str(c['customer_name']), border=1)
            pdf.cell(90, 10, f"${float(c['revenue']):,.2f}", border=1, ln=True, align="R")
        pdf.ln(10)

    # --- Customer Risk Lists ---
    if filtered_risk_lists and any(filtered_risk_lists.values()):
        pdf.add_page()
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "Risk Category Analysis", ln=True)
        pdf.ln(5)
        
        for risk, customers in filtered_risk_lists.items():
            if not customers:
                continue
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(0, 10, f"{risk} Customers ({len(customers)})", ln=True)
            
            pdf.set_font("helvetica", "", 10)
            for c in customers:
                line = f"- {c['name']}: ${c['revenue']:,.2f}  |  {c.get('reason', '')}"
                pdf.multi_cell(0, 6, line)
            pdf.ln(5)

    # Output to essentially a BytesIO buffer
    pdf_string = pdf.output(dest="S") # 'S' returns a string in fpdf 1.x
    if isinstance(pdf_string, str):
        return pdf_string.encode('latin-1')
    return pdf_string
